
@startuml
package "Components" {
    class Component {
    }

    class Velocity implements Component {
        +x: int
        +y: int
        +z: int
    }

    class Position implements Component {
        +x: int
        +y: int
        +z: int
    }

}

package "Entities" {
    class Entity {
        +id: int
    }
}

package "Chunks" {
    class Chunk {
        +archetypeType: Archetype*
        +entityCount: int
        +entities: std::array<Entity>
    }

    class VelPosChunk implements Chunk {
        +archetypeType: VelPosArchetype*
        +entityCount: int
        +entities: std::array<Entity>
        +velocities: array<Velocity>
        +positions: array<Position>
        +versionVelocities: uint32_t
        +versionPositions: uint32_t
    }

    class ChunkX implements Chunk {
        +archetypeType: ArchetypeX*
        +entityCount: int
        +entities: std::array<Entity>
        +componentsX: std::array<ComponentX>
        +versionComponentX: uint32_t
    }
}

package "Archetypes" {
    class Archetype {
        +maxEntities: int
        +id: int
        +componentMask: uint32
        +chunks: std::list<chunk>
    }

    class VelPosArchetype implements Archetype {
        +maxEntities: int
        +id: int
        +componentMask: uint16
    }

    class VelHealthArchetype implements Archetype {
        +maxEntities: int
        +id: int
        +componentMask: uint16
    }

    class ArchetypeX implements Archetype {
        +maxEntities: int
        +id: int
        +componentMask: uint16
    }
}

package "Systems" {
    class System {
        +update()
    }
}

    VelPosChunk --> VelPosArchetype
    
@enduml
